#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-randomForest
Version  : 4.6.12
Release  : 31
URL      : http://cran.r-project.org/src/contrib/randomForest_4.6-12.tar.gz
Source0  : http://cran.r-project.org/src/contrib/randomForest_4.6-12.tar.gz
Summary  : Breiman and Cutler's Random Forests for Classification and
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: R-randomForest-lib
BuildRequires : clr-R-helpers

%description
No detailed description available

%package lib
Summary: lib components for the R-randomForest package.
Group: Libraries

%description lib
lib components for the R-randomForest package.


%prep
%setup -q -c -n randomForest

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489129563

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1489129563
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library randomForest
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library randomForest


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/randomForest/CITATION
/usr/lib64/R/library/randomForest/DESCRIPTION
/usr/lib64/R/library/randomForest/INDEX
/usr/lib64/R/library/randomForest/Meta/Rd.rds
/usr/lib64/R/library/randomForest/Meta/data.rds
/usr/lib64/R/library/randomForest/Meta/hsearch.rds
/usr/lib64/R/library/randomForest/Meta/links.rds
/usr/lib64/R/library/randomForest/Meta/nsInfo.rds
/usr/lib64/R/library/randomForest/Meta/package.rds
/usr/lib64/R/library/randomForest/NAMESPACE
/usr/lib64/R/library/randomForest/NEWS
/usr/lib64/R/library/randomForest/R/randomForest
/usr/lib64/R/library/randomForest/R/randomForest.rdb
/usr/lib64/R/library/randomForest/R/randomForest.rdx
/usr/lib64/R/library/randomForest/data/imports85.rda
/usr/lib64/R/library/randomForest/help/AnIndex
/usr/lib64/R/library/randomForest/help/aliases.rds
/usr/lib64/R/library/randomForest/help/paths.rds
/usr/lib64/R/library/randomForest/help/randomForest.rdb
/usr/lib64/R/library/randomForest/help/randomForest.rdx
/usr/lib64/R/library/randomForest/html/00Index.html
/usr/lib64/R/library/randomForest/html/R.css
/usr/lib64/R/library/randomForest/libs/symbols.rds

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/randomForest/libs/randomForest.so
